### ISSUE TITLE
pbs fetcher error

### ISSUE THREAD

**Issue by zimmerst** [zimmerst/DmpWorkflow#29]
fetcher fails to retrieve valid xml
```python
Traceback (most recent call last):
  File "/atlas/software/dampe/externals/virtualEnvs/DAMPE/bin/dampe-cli-fetch-new-jobs", line 10, in <module>
    sys.exit(main())
  File "/atlas/software/dampe/externals/virtualEnvs/DAMPE/lib/python2.7/site-packages/DmpWorkflow/scripts/dampe_cli_fetch_new_jobs.py", line 30, in main
    val = len(BEngine.getRunningJobs(pending=True))
  File "/atlas/software/dampe/externals/virtualEnvs/DAMPE/lib/python2.7/site-packages/DmpWorkflow/hpc/pbs.py", line 75, in getRunningJobs
    self.update()
  File "/atlas/software/dampe/externals/virtualEnvs/DAMPE/lib/python2.7/site-packages/DmpWorkflow/hpc/pbs.py", line 51, in update
    self.allJobs.update(self.aggregateStatii())
  File "/atlas/software/dampe/externals/virtualEnvs/DAMPE/lib/python2.7/site-packages/DmpWorkflow/hpc/pbs.py", line 125, in aggregateStatii
    return self.__parseOutputAsXml__(output, checkUser)
  File "/atlas/software/dampe/externals/virtualEnvs/DAMPE/lib/python2.7/site-packages/DmpWorkflow/hpc/pbs.py", line 83, in __parseOutputAsXml__
    output = xml2dict.parse(xmloutput)
  File "/atlas/software/dampe/externals/virtualEnvs/DAMPE/lib/python2.7/site-packages/xmltodict.py", line 311, in parse
    parser.Parse(xml_input, True)
xml.parsers.expat.ExpatError: no element found: line 242, column 61
```

**Comment by zimmerst** [comment]
this is partly remedied by 0bd8b57; instead of using the batch engine, a DB connection is used to get the jobs registered as running/ suspended/ pending instead. this can be skipped in the script. However, the root cause still needs to be understood.
